name: j_flutter_ui_example
description: Example app for the j_flutter_ui package.
publish_to: 'none'

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  j_flutter_ui:
    path: ../
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
